services:
  gitlab:
    image: docker.io/gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: "${GITLAB_HOST}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://${GITLAB_HOST}:8929"
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['enable_gitlab_pages'] = false
        gitlab_rails['enable_gitlab_ci'] = false
        gitlab_rails['enable_gitlab_monitor'] = false
        gitlab_rails['enable_gitlab_kas'] = false
        gitlab_rails['enable_gitlab_webhooks'] = false
    ports:
      - "8929:8929"
      - "8443:443"
      - "2424:22"
    volumes:
      - "$GITLAB_HOME/config:/etc/gitlab"
      - "$GITLAB_HOME/logs:/var/log/gitlab"
      - "$GITLAB_HOME/data:/var/opt/gitlab"
    shm_size: "256m"
